{% set version = '0.4.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-erify
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/erify_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/erify/erify_{{ version }}.tar.gz
  sha256: 7a2e7203f1d6ba174215746ccbb9d40a5110153274e54a96235124e532239804

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-glue
  run:
    - r-base
    - r-glue

test:
  commands:
    - $R -e "library('erify')"           # [not win]
    - "\"%R%\" -e \"library('erify')\""  # [win]

about:
  home: https://flujoo.github.io/erify/
  dev_url: https://github.com/flujoo/erify
  license: MIT
  summary: Provides several validator functions for checking if arguments passed by users have
    valid types, lengths, etc. and for generating informative and well-formatted error
    messages in a consistent style. Also provides tools for users to create their own
    validator functions. The error message style used is adopted from <https://style.tidyverse.org/error-messages.html>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: erify
# Type: Package
# Title: Check Arguments and Generate Readable Error Messages
# Version: 0.4.0
# Author: Renfei Mao
# Maintainer: Renfei Mao <renfeimao@gmail.com>
# Description: Provides several validator functions for checking if arguments passed by users have valid types, lengths, etc. and for generating informative and well-formatted error messages in a consistent style. Also provides tools for users to create their own validator functions. The error message style used is adopted from <https://style.tidyverse.org/error-messages.html>.
# License: MIT + file LICENSE
# URL: https://github.com/flujoo/erify, https://flujoo.github.io/erify/
# Encoding: UTF-8
# RoxygenNote: 7.2.1
# Imports: glue
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2022-10-04 12:12:47 UTC; flujoo
# Repository: CRAN
# Date/Publication: 2022-10-04 12:30:07 UTC
